CREATE TABLE EMPLOYEE2
(JOBTYPE varchar(30) NOT NULL,
SALARY INT,
PRIMARY KEY(JOBTYPE));

--INSERTING VALUES INTO TABLE: EMPLOYEE2--
INSERT INTO EMPLOYEE2(JOBTYPE, SALARY)VALUES('ADMINISTRATIVE SUPPORT',50000);
INSERT INTO EMPLOYEE2(JOBTYPE, SALARY)VALUES('ENGINEER',70000);
INSERT INTO EMPLOYEE2(JOBTYPE, SALARY)VALUES('TRAFFIC MONITOR',80000);
INSERT INTO EMPLOYEE2(JOBTYPE, SALARY)VALUES('AIRPORT AUTHORITY',90000);